// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"

	"github.com/google/uuid"
)

type Credential struct {
	ID              uuid.UUID
	Email           string
	EmailIsVerified bool
	PasswordHash    string
	CreatedAt       time.Time
}

type EmailVerificationToken struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Session struct {
	ID            uuid.UUID
	CredentialsID uuid.UUID
	Token         string
	CsrfToken     string
	CreatedAt     time.Time
}

type User struct {
	ID            uuid.UUID
	Name          string
	Username      string
	CredentialsID uuid.UUID
	CreatedAt     time.Time
}
