// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx.sql

package repo

import (
	"context"
)

const begin = `-- name: Begin :exec
begin
`

func (q *Queries) Begin(ctx context.Context) error {
	_, err := q.exec(ctx, q.beginStmt, begin)
	return err
}

const commit = `-- name: Commit :exec
commit
`

func (q *Queries) Commit(ctx context.Context) error {
	_, err := q.exec(ctx, q.commitStmt, commit)
	return err
}

const rollback = `-- name: Rollback :exec
rollback
`

func (q *Queries) Rollback(ctx context.Context) error {
	_, err := q.exec(ctx, q.rollbackStmt, rollback)
	return err
}
