// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	SessionToken string
	CsrfToken    string
	CreatedAt    time.Time
	UserAgent    string
	IpAddress    string
	LastActive   time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Username     string
	Email        string
	PasswordHash string
	Verified     bool
	JoinedAt     time.Time
}
