// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkEmail = `-- name: CheckEmail :one
select exists (select 1 from users where email = $1 for update)
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.checkEmailStmt, checkEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsername = `-- name: CheckUsername :one
select exists (select 1 from users where username = $1 for update)
`

func (q *Queries) CheckUsername(ctx context.Context, username string) (bool, error) {
	row := q.queryRow(ctx, q.checkUsernameStmt, checkUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
delete from email_verification_tokens where expires_at <= now()
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredEmailVerificationTokensStmt, deleteExpiredEmailVerificationTokens)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
delete from users where id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteUserByIDStmt, deleteUserByID, id)
	return err
}

const getEmailVerificationTokenByID = `-- name: GetEmailVerificationTokenByID :one
select id, user_id, created_at, expires_at from email_verification_tokens where id = $1
`

func (q *Queries) GetEmailVerificationTokenByID(ctx context.Context, id uuid.UUID) (EmailVerificationToken, error) {
	row := q.queryRow(ctx, q.getEmailVerificationTokenByIDStmt, getEmailVerificationTokenByID, id)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, name, username, email, password_hash, email_is_verified, joined_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailIsVerified,
		&i.JoinedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, name, username, email, password_hash, email_is_verified, joined_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailIsVerified,
		&i.JoinedAt,
	)
	return i, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
insert into email_verification_tokens (id, user_id, created_at, expires_at)
values ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.exec(ctx, q.insertEmailVerificationTokenStmt, insertEmailVerificationToken,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
insert into users (id, name, username, email, password_hash)
values ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID           uuid.UUID
	Name         string
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.exec(ctx, q.insertUserStmt, insertUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const markEmailAsVerified = `-- name: MarkEmailAsVerified :exec
update users set email_is_verified = true where id = $1
`

func (q *Queries) MarkEmailAsVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.markEmailAsVerifiedStmt, markEmailAsVerified, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
update users 
set
    name = $1,
    username = $2,
    email = $3,
    password_hash = $4
where id = $5
`

type UpdateUserParams struct {
	Name         string
	Username     string
	Email        string
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.ID,
	)
	return err
}
